### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pssguy** [atlas-aai/ratlas#41]
```
remotes::install_github("atlas-aai/ratlas")
```
Error: Failed to install 'unknown package' from GitHub: HTTP error 404. No commit found for the ref master Did you spell the repo owner (`atlas-aai`) and repo name (`ratlas`) correctly? - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by wjakethompson** [comment]
Sorry for the delayed response! I'm unable to reproduce now, but this likely related to when I switched the default branch from `master` to `main`. At the time, `remotes::install_github()` still used `ref = "master"` as the default. So your code above would have tried to install from the `master` branch of `atlas-aai/ratlas`, which no longer exists.

The {remotes} package has since been updated to reference the HEAD branch (i.e., the default; see r-lib/remotes#510), so updating {remotes} should solve the problem. Alternatively `remotes::install_github("atlas-aai/ratlas@main")` will force an install off of the `main` branch.
